---
name: Build Docker images pipeline
on:
  workflow_call:
    inputs:
      arch:
        description: "Architecture we want to build for"
        required: true
        type: string
      version:
        description: 'What is the version used to build and tag the RPMs'
        required: true
        type: string
      release-version:
        description: 'What is the release version used to build and tag the RPMs'
        required: true
        type: string

      build_rpm:
        type: boolean
        required: false
        default: true

      build_deb:
        type: boolean
        required: false
        default: true

      move_latest_tag:
        description: 'Whether to move the latest tag'
        type: boolean
        required: false
        default: true

env:
  GOSS_VERSION: v0.4.9

jobs:

  setup:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.prepare-matrix.outputs.matrix }}
    steps:
      - id: prepare-matrix
        run: |
          MATRIX='[]'

          if [[ "${{ inputs.build_rpm }}" == "true" ]]; then
            MATRIX=$(jq -c '. += [
              {
                "name":"ubi10.1",
                "type":"rpm",
                "path":"docker/ubi",
                "base-image":"registry.access.redhat.com/ubi10-micro:10.1",
                "builder-image":"registry.access.redhat.com/ubi10:10.1",
                "libssl-version":3,
                "libcrypto-version":3,
                "latest_tag":"${{ inputs.move_latest_tag }}"
              },
              {
                "name":"ubi9.6",
                "type":"rpm",
                "path":"docker/ubi",
                "base-image":"registry.access.redhat.com/ubi9-micro:9.6",
                "builder-image":"registry.access.redhat.com/ubi9:9.6",
                "libssl-version":3,
                "libcrypto-version":3,
                "latest_tag":"${{ inputs.move_latest_tag }}"
              },
              {
                "name":"fc43",
                "type":"rpm",
                "path":"docker/fedora",
                "base-image":"fedora:43"
              }
            ]' <<< "$MATRIX")
          fi

          if [[ "${{ inputs.build_deb }}" == "true" ]]; then
            MATRIX=$(jq -c '. += [
              {
                "name":"debian_13",
                "type":"deb",
                "path":"docker/debian",
                "base-image":"debian:13-slim"
              },
              {
                "name":"ubuntu_24.04",
                "type":"deb",
                "path":"docker/ubuntu",
                "base-image":"ubuntu:24.04"
              }
            ]' <<< "$MATRIX")
          fi

          echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"
  packaging:
    name: packaging (${{ matrix.os.name }})
    runs-on: ${{ inputs.arch == 'x86_64' && 'ubuntu-24.04' || inputs.arch == 'aarch64' && 'ubuntu-24.04-arm'}}
    timeout-minutes: 30
    outputs:  
      artifact_name: ${{ steps.artifact_name.outputs.OUTPUT_ARTIFACT_NAME }}
    env:
      ARCH: ${{ (inputs.arch == 'x86_64' && matrix.os.type == 'deb') && 'amd64' || (inputs.arch == 'aarch64' && matrix.os.type == 'deb') && 'arm64' || inputs.arch }}
      DOCKER_BUILD_PLATFORM: ${{ (inputs.arch == 'x86_64') && 'linux/amd64' || 'linux/arm64' }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.setup.outputs.matrix) }}
    needs:
      - setup

    steps:
      # See deb and rpm steps.
      - name: Normalize version number
        run: |
          # Allowed characteres for image tag are: [a-zA-Z0-9_.-]
          SANITIZED_VERSION=$(echo ${{ inputs.version }} | sed 's/[\^\+_]/-/g')
          echo "SANITIZED_VERSION=$SANITIZED_VERSION" >> "$GITHUB_ENV"
          echo "SANITIZED_VERSION=$SANITIZED_VERSION"

      - name: Checkout the repository
        uses: actions/checkout@v7
        with:
          repository: guigomcha/alumet-packaging
          branch: custom-build

      - name: Define the dependency artifact pattern
        run: |
          if [[ ${{ matrix.os.type }} == 'rpm' ]]; then
            echo "DEPS_ARTIFACT_PATTERN=alumet-agent-*-${{ inputs.release-version }}.${{ matrix.os.name }}.${{ env.ARCH }}.rpm" >> "$GITHUB_ENV"
          else
            echo "DEPS_ARTIFACT_PATTERN=alumet-agent_*-${{ inputs.release-version }}_${{ env.ARCH }}_${{ matrix.os.name }}.deb" >> "$GITHUB_ENV"
          fi

      - name: Define the output artifact name
        id: artifact_name
        run: |
          echo "OUTPUT_ARTIFACT_NAME=alumet-agent-${{ inputs.version }}-${{ inputs.release-version }}.${{ matrix.os.name }}.${{ inputs.arch }}.docker.tar" >> "$GITHUB_OUTPUT"

      - name: Create the dependency artifacts directory
        run: mkdir -p build/deps-artifacts

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          pattern: ${{ env.DEPS_ARTIFACT_PATTERN }}
          path: ${{ matrix.os.path }}

      - name: Locate downloaded file
        run: |
          FILE=$(find "${{ matrix.os.path }}" -maxdepth 1 -type f \( -name '*.rpm' -o -name '*.deb' \) | head -n1)
          echo "DEPS_ARTIFACT_FILE=$(basename "$FILE")" >> "$GITHUB_ENV"

      - name: Create docker image output dir
        run: mkdir -p build/docker
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up image tags
        run: |
          TAGS="ghcr.io/${{ github.repository_owner }}/alumet-agent:${{ env.SANITIZED_VERSION }}-${{ inputs.release-version }}_${{ matrix.os.name }}_${{ inputs.arch }}"
          if [ "${{ matrix.os.latest_tag }}" == "true" ]; then
            TAGS="$TAGS,ghcr.io/${{ github.repository_owner }}/alumet-agent:latest_${{ inputs.arch }}"
          fi
          echo "TAGS=$TAGS" >> "$GITHUB_ENV"
          echo "Images tags: $TAGS" >> "$GITHUB_STEP_SUMMARY"

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.os.path }}
          push: false
          platforms: ${{ env.DOCKER_BUILD_PLATFORM }}
          file: ${{ matrix.os.path }}/Dockerfile
          build-args: |
            ALUMET_VERSION=${{ inputs.version }}
            BUILDER_IMAGE=${{ matrix.os.builder-image }}
            BASE_IMAGE=${{ matrix.os.base-image }}
            ARTIFACT_FILE=${{ env.DEPS_ARTIFACT_FILE }}
            LIBSSL_VERSION=${{ matrix.os.libssl-version }}
            LIBCRYPTO_VERSION=${{ matrix.os.libcrypto-version }}
          outputs: type=docker,dest=build/docker/${{ steps.artifact_name.outputs.OUTPUT_ARTIFACT_NAME }}
          tags: ${{ env.TAGS }}
        env:
          DOCKER_BUILD_SUMMARY: false

      - name: Upload docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact_name.outputs.OUTPUT_ARTIFACT_NAME }}
          path: ./build/docker/${{ steps.artifact_name.outputs.OUTPUT_ARTIFACT_NAME }}

  testing:
    runs-on: ${{ inputs.arch == 'x86_64' && 'ubuntu-24.04' || inputs.arch == 'aarch64' && 'ubuntu-24.04-arm'}}
    timeout-minutes: 10
    env:
      DOCKER_ARTIFACT_NAME: alumet-agent-${{ inputs.version }}-${{ inputs.release-version }}.${{ matrix.os.name }}.${{ inputs.arch }}.docker.tar
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.setup.outputs.matrix) }}

    needs:
      - setup
      - packaging

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7
        with:
          repository: guigomcha/alumet-packaging
          branch: custom-build

      - name: Create docker artifacts directory
        run: mkdir docker-artifacts

      - name: Download docker images artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.packaging.outputs.artifact_name }}
          path: ./docker-artifacts
      
      - name: Install Dgoss
        env:
          ARCH: ${{ inputs.arch == 'x86_64' && 'amd64' || inputs.arch == 'aarch64' && 'arm64'}}
        run: |
          curl -L "https://github.com/goss-org/goss/releases/download/${GOSS_VERSION}/goss-linux-${{ env.ARCH }}" -o /usr/local/bin/goss
          chmod +rx /usr/local/bin/goss

          curl -L "https://github.com/goss-org/goss/releases/download/${GOSS_VERSION}/dgoss" -o /usr/local/bin/dgoss
          chmod +rx /usr/local/bin/dgoss

          echo "/usr/local/bin" >> "$GITHUB_PATH"

      - name: Run Dgoss tests
        run: |
          image_sha=$(docker load -q -i ./docker-artifacts/${{ needs.packaging.outputs.artifact_name }} | grep "Loaded image: "| awk '{ print $3 }' | head -1)
          export GOSS_FILE=.github/dgoss_validate.yaml
          set -o pipefail
          dgoss run  --cap-add=sys_ptrace --cap-add=perfmon --cap-add=sys_nice "$image_sha" 2>&1 | tee ${{ matrix.os.name }}-${{ inputs.arch }}-dgoss_tests_report.txt >> "$GITHUB_STEP_SUMMARY"

      - name: Upload tests reports
        if: always() # never skip to have file even in case of test failure
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os.name }}-${{ inputs.arch }}-dgoss_tests_report.txt
          path: ${{ matrix.os.name }}-${{ inputs.arch }}-dgoss_tests_report.txt
