---
name: Build RPM pipeline
on:
  workflow_call:
    inputs:
      arch:
        description: "Architecture we want to build for"
        required: true
        type: string

      version:
        description: "Application version (version of the alumet agent)"
        required: true
        type: string

      release-version:
        description: "Package release number (increase it when you update the package with the same app version)"
        required: true
        type: string

      tag:
        description: "The tag used to checkout the correct version of source code"
        required: false
        type: string
        default: 'main'

      rust-version:
        description: "Version of Rust to compile Alumet with"
        type: string
        default: '1.89'

env:
  ACT: false
  GOSS_VERSION: v0.4.9

jobs:
  setup:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.prepare-matrix.outputs.matrix }}
    steps:
      - id: prepare-matrix
        run: |
          MATRIX='[]'
          MATRIX=$(jq -c '. += [
            {
              "name":"fc42",
              "base-image":"fedora:42"
            },
            {
              "name":"fc43",
              "base-image":"fedora:43"
            },
            {
              "name":"ubi8.10", 
              "base-image":"registry.access.redhat.com/ubi8/ubi:8.10"
            },
            {
              "name":"ubi9.6", 
              "base-image":"registry.access.redhat.com/ubi9/ubi:9.6"
            },
            {
              "name":"ubi10.1", 
              "base-image":"registry.access.redhat.com/ubi10/ubi:10.1"
            }
          ]' <<< "$MATRIX")
          echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"
  rpm-packaging:
    runs-on: ${{ inputs.arch == 'x86_64' && 'ubuntu-24.04' || inputs.arch == 'aarch64' && 'ubuntu-24.04-arm'}}
    continue-on-error: true
    needs: 
      - setup
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.setup.outputs.matrix) }}
    env:
      pkg_name: alumet-agent
    container:
      image: ${{ matrix.os.base-image }}
    steps:
      - name: Install Act dependencies
        if: ${{ env.ACT }}
        run: |
          dnf install --setopt=install_weak_deps=False -y nodejs sudo

      # replace some forbidden characters with ~
      # also replace - by ~ because we want 1.2.3-defbcda to be sorted BEFORE 1.2.3
      - name: Normalize version number
        run: |
          PKG_VERSION=$(echo ${{ inputs.version }} | sed 's/[_-]/~/g')
          echo "PKG_VERSION=$PKG_VERSION" >> "$GITHUB_ENV"
          echo "PKG_VERSION=$PKG_VERSION"

      - uses: actions/checkout@v7
        with:
          repository: guigomcha/alumet-packaging
          fetch-tags: true
          path: 'packaging'
          branch: custom-build
          fetch-depth: 1

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs  | sh -s -- -y --profile minimal --default-toolchain ${{ inputs.rust-version }}

      - name: Install Fedora dependencies
        if: contains(matrix.os.base-image, 'fedora')
        run: sudo dnf install --setopt=install_weak_deps=False -y rpm-build openssl-devel gcc git

      - name: Install non-Fedora dependencies
        if: ${{ ! contains(matrix.os.base-image, 'fedora') }}
        run: |
          yum install -y --allowerasing unzip rpm-build openssl-devel curl gcc git

      - name: Setup for alumet sources
        run: mkdir -p alumet

      - name: Checkout alumet repo
        uses: actions/checkout@v7
        with:
          repository: guigomcha/alumet
          path: "alumet"
          ref: '${{ inputs.tag }}'
          fetch-depth: 1
          fetch-tags: true

      - name: Compile Alumet agent
        working-directory: alumet
        run: |
          . "$HOME/.cargo/env"
          bin=$(pwd)/bin
          mkdir "$bin"
          CARGO_TARGET_DIR="$bin" ALUMET_AGENT_RELEASE=true RUSTFLAGS="-Awarnings" cargo build --release -p alumet-agent
          cp "$bin/release/alumet-agent" ../packaging/rpm/SOURCES/alumet-agent

      - name: Build RPM package
        id: build-rpm-package
        env:
          build_dir: "$(pwd)/build"
          source_dir: "$(pwd)/SOURCES"
        working-directory: packaging/rpm
        run: |
          rpmbuild -bb -vv --define "_topdir ${{ env.build_dir }}" --define "_sourcedir ${{ env.source_dir }}" --define "_libdir /usr/lib" --define "version ${{ env.PKG_VERSION }}" --define "release ${{ inputs.release-version }}" --define "osr ${{ matrix.os.name }}" --define "arch ${{ inputs.arch }}" SPECS/alumet.spec
          export FILENAME="${{ env.pkg_name }}-${{ env.PKG_VERSION }}-${{ inputs.release-version }}.${{ matrix.os.name }}.${{ inputs.arch }}.rpm"
          echo "PACKAGE_FILENAME=$FILENAME" >> "$GITHUB_OUTPUT"
          echo "PACKAGE_PATH=$(pwd)/build/RPMS/${{ inputs.arch }}/$FILENAME" >> "$GITHUB_OUTPUT"

      - name: Upload artifact alumet-agent
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build-rpm-package.outputs.PACKAGE_FILENAME }}
          path: ${{ steps.build-rpm-package.outputs.PACKAGE_PATH }}
          compression-level: 0  # the package is already compressed

  rpm-testing:
    runs-on: ${{ inputs.arch == 'x86_64' && 'ubuntu-24.04' || inputs.arch == 'aarch64' && 'ubuntu-24.04-arm'}}
    needs:
      - setup
      - rpm-packaging
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.setup.outputs.matrix) }}
    container:
      image: ${{ matrix.os.base-image }}
      options: --cap-add=SYS_NICE --cap-add=PERFMON --cap-add=SYS_PTRACE

    steps:
      - name: Install Act dependencies
        if: ${{ env.ACT }}
        run: |
          dnf install --setopt=install_weak_deps=False -y nodejs sudo

      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          repository: 'alumet-dev/packaging'
          fetch-depth: 1
          path: 'packaging'

      - name: Download RPM artifact
        id: download_rpm
        uses: actions/download-artifact@v4
        with:
          pattern: '**/*${{ matrix.os.name }}.${{ inputs.arch }}.rpm'
          path: ./rpm
          merge-multiple: true

      - name: Install systemd on Fedora
        if: contains(matrix.os.base-image, 'fedora')
        run: |
          dnf install -y systemd

      - name: Install RPMs
        run: |
          dnf install -y ${{ steps.download_rpm.outputs.download-path }}/*.rpm

      - name: Install Goss
        env:
          ARCH: ${{ inputs.arch == 'x86_64' && 'amd64' || inputs.arch == 'aarch64' && 'arm64'}}
        run: |
          curl -L "https://github.com/goss-org/goss/releases/download/${GOSS_VERSION}/goss-linux-${{ env.ARCH }}" -o /usr/local/bin/goss
          chmod +rx /usr/local/bin/goss

          echo "/usr/local/bin" >> "$GITHUB_PATH"

      - name: Run Goss tests
        id: goss-tests
        run: |
          set -o pipefail
          goss -g packaging/.github/goss_validate.yaml validate --format documentation | tee goss-results-rpm-${{ matrix.os.name }}.txt >> "$GITHUB_STEP_SUMMARY"

      - name: Upload goss report
        if: >-
          always() &&
          steps.goss-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: goss-results-rpm-${{ matrix.os.name }}.txt
          path: |
            ./goss-results-rpm-${{ matrix.os.name }}.txt
